# .github/workflows/deploy.yml

name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # ✅ Step 1: Get pods via K8s API
     
      # Step 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./problem1
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${{ github.sha }}

      # Step 6: Rollout restart via API
      - name: Rollout restart via API
        run: |
          NAMESPACE="default"
          DEPLOYMENT="wisecow"
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      
          curl -k -XPATCH https://kubernetes.default.svc/apis/apps/v1/namespaces/$NAMESPACE/deployments/$DEPLOYMENT \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/strategic-merge-patch+json" \
            -d '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"'"$(date -Iseconds)"'"}}}}}'
