# .github/workflows/deploy.yml

name: Build, Push, and Deploy to Kubernetes


on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
   
    runs-on: self-hosted

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./problem1
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app-name:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app-name:${{ github.sha }}

      
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment wisecow 
